flags: {}
packages:
- '.'
- location:
    git: git@github.com:cies/htoml.git
    commit: 8f8dc5e92571bc51055f4df35533a3fd2a23e691
  extra-dep: true
extra-deps:
- recursion-schemes-4.1.2
resolver: lts-3.13
